#!/system/bin/sh
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#  Copyright (C) 2017 MUHAMMAD IRHAM F (TORMENT) All Rights Reserved
#  GUNAKAN TWEAKS INI SEBIJAK MUNGKIN, DAN JANGAN MENCURI :]
#=======================================================================#
# Original Script written by clvv <x@wei23.net> 
# Modified Script written by Muhammad Irham <cuman-android.blogspot.co.id>
busybox mount -o remount,rw /system > /dev/null
busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
#garis
garis1="\e[0;100m========================================\e[00;37;40m"
path=/system/etc/init.d
gpupath=/system/etc/NGZ/NGZCPGP
#PATHCEK
if [ -e $path/90gt ];then
	gpud="\e[1;32mValue Di Simpan\e[0m"
else
	gpud="\e[1;31mValue Belum Simpan\e[0m"
fi
	busybox clear
	busybox echo -n "Lanjutkan Proses ? (yes/no) : "
	read baca
	if [ $baca = "yes" ];then
	busybox clear
	busybox echo -e $garis1
	busybox echo -e "\e[1;32mGOVERNOR TUNER\e[00;37;40m"
	busybox echo -e $garis1
	busybox echo ""
	#path
	gv=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors)
	#value
	busybox echo -n "Tipe Governor saat ini: "; cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	busybox echo ""
	busybox echo -e "Kondisi GPU Tuner || $gpud"
	busybox echo ""
	busybox echo -e $garis1
	busybox echo ""
	busybox echo -e "Tipe Governor yang tersedia: "
	busybox echo ""
#####OURSHIT#####
max=10
for number in `seq 1 $max`
do
angka=`awk '{print $'$number'}' /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors`
if [ -z $angka ];then
echo $number. Tidak Tersedia
else
echo $number. $angka
fi
done
#################

	busybox echo ""
	busybox echo -e $garis1
	#change value
	busybox echo ""
	busybox echo -n "Masukan Tipe Governor : "
	read gvnr
    if [ $gvnr ]; then
    if [ $(echo $gv | grep -q -E "$gvnr"; echo $?) -eq 0 ]; then
    echo $gvnr > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 
	busybox echo ""
	busybox echo -e $garis1
	busybox echo ""
	busybox echo "============================================"
	busybox echo -e "\e[1;32mFREKUENSI GPU TERBARU\e[00;37;40m"
	busybox echo "============================================"
	busybox echo ""
	busybox echo -n "Frekuensi GPU saat ini: "; 
	busybox echo $gvnr | awk '{print}' 
	busybox echo ""
	busybox echo -n "Aktifkan saat reboot ? (yes/no) : " 
	read mnu
    if [ $mnu = "yes" ];then
    if [ -e $path/90gt ];then
     busybox rm -rf $path/90gt
	fi
	
busybox touch $path/90gt
busybox chmod 755 $path/90gt
busybox cat > $path/90gt << gpuyahud
busybox mount -o remount,rw / 2>/dev/null
busybox mount -o remount,rw /system 2>/dev/null
busybox mount -o remount,rw rootfs 2>/dev/null
busybox echo "$gvnr" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 
gpuyahud
	
	sh $path/90gt
	elif [ $mnu = "no" ]; then
	if [ -e $path/90gt ];then
     busybox rm -rf $path/90gt
	fi
	busybox sleep 1
	else
	busybox sleep 1
	fi
    else
	busybox echo ""
	busybox echo "Waduh valuenya salah tuh, ulangi lagi ya"
	busybox sleep 2
	busybox clear
	busybox sh $gpupath/00NGZgpu
    fi
    fi
	busybox echo ""
	busybox echo "Proses selesai, kembali..."
	busybox sleep 2
	busybox sh /system/bin/11ngz
   elif [ $baca = "no" ];then
   busybox clear
   busybox echo "Proses tidak di lanjutkan, kembali..."
   busybox sleep 2
   busybox sh /system/bin/11ngz
   else
   busybox clear
   busybox echo "Maaf, harap ulangi inputan anda"
   busybox sleep 2
   busybox clear
   sh $gpupath/00NGZgpu
   fi