#!/system/bin/sh
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#  Copyright (C) 2017 MUHAMMAD IRHAM F (TORMENT) Cuman Android All Rights Reserved
#  GUNAKAN TWEAKS INI SEBIJAK MUNGKIN, DAN JANGAN MENCURI :]
#=======================================================================#

busybox mount -o remount,rw / 2>/dev/null
busybox mount -o remount,rw rootfs 2>/dev/null
busybox mount -o remount,rw /system 2>/dev/null

		busybox find /data/data -type d -iname "*cache*" -maxdepth 2 -mindepth 2 -exec busybox rm -fr {}/ ';' 
		busybox rm -f /data/slog/* 2>/dev/null 
		busybox rm -f /data/system/dropbox/*.* 2>/dev/null
		busybox rm -f /data/mlog/* 2>/dev/null
		busybox rm -f /data/log/*.* 2>/dev/null
		busybox rm -f /dev/log/main/* 2>/dev/null
		busybox rm -f /data/backup/pending/*.tmp 2>/dev/null
		busybox rm -f /data/tombstones/*.* 2>/dev/null
     busybox rm -f /data/last_alog/* 2>/dev/null
     busybox rm -f /data/last_kmsg/* 2>/dev/null
		busybox rm -f /data/local/*.apk 2>/dev/null
		busybox rm -f /data/local/tmp/* 2>/dev/null
		buysbox rm -f /data/anr/* 2>/dev/null 
     busybox rm -f /cache/*.apk 2>/dev/null
     busybox rm -f /cache/*.tmp 2>/dev/null
     busybox rm -f /data/data/*/cache/* 2>/dev/null
     busybox rm -f /data/clipboard/* 2>/dev/null
     busybox rm -f /dev/log/main/* 2>/dev/null
     busybox rm -f /data/mlog/* 2>/dev/null
     busybox rm -f /data/cache/*.* 2>/dev/null
     busybox rm -f /data/log/* 2>/dev/null
     busybox rm -f /data/system/dropbox/* 2>/dev/null
     busybox rm -f /cache/*.log 2>/dev/null
     busybox rm -f /data/system/usagestats/* 2>/dev/null
